### ISSUE TITLE
Keyboard does not appear after some actions

### ISSUE THREAD

**Issue by tral** [rengwuxian/MaterialEditText#171]
I have MaterianEditText in my Activity1.
I call Activity2 from Activity1. After closing Activity2 there is no way to show keyboard when tapping on MaterianEditText (which is placed in Activity1). Keyboard doesn't appear.

**Comment by rengwuxian** [comment]
Does this happen when you use EditText instead of MaterialEditText?

**Comment by tral** [comment]
No. I am temporary using EditText instead of MaterialEditText exactly because of this problem. With EditText everything is ok.

**Comment by tral** [comment]
Small notice: if you have 2 or more MaterialEditTexts in Activity1, you can tap another one and it works.
So, if you have mEt1 and mEt2 in Activity1 and mEt1 is focused , then you show Activity2, close it, mEt1 is still focused but you cannot open keyboard. If you tap on mEt2 - you'll see the keyboard, then tap on mEt1 again - you'll alsoo see the keyborad. But if there is only one MaterialEditText in your Activity - trick doesn't work.

**Comment by rengwuxian** [comment]
Clear description. I'll take a look. Thanks.

**Comment by squeeish** [comment]
I've the same problem. There's only 1 MaterialEditText in my layout. After going to SettingsActivity and returning, MaterialEditText does not work. No errors that I can see in logcat.

**Comment by mvarnagiris** [comment]
Same issue for me. Just leaving a comment to track the issue progress.

**Comment by ayuhe** [comment]
Same issue for me. How to solve the problem?

**Comment by rengwuxian** [comment]
Fixed in `v2.1.4`. I just uploaded it, and it should be synced to Maven Central in several hours.

It's because of the clear button. Thanks to @onewilk for helping me repro this issue on my device in #201 .

**Comment by ayuhe** [comment]
Hi, Yes I have been verified, it is OK. Thanks.

**Comment by hscissors** [comment]
I'm still experience errors with this. I have a single MaterialEditText in a single LinearLayout. Theme base is Theme.Holo, 4.4.4, No custom keyboard.

**Comment by akbarsha03** [comment]
Same issue here :disappointed: I forked today

**Comment by hscissors** [comment]
@akbarsha03 the problem was that you have to use the AppCompat theme.

**Comment by exequielc** [comment]
Same issue here!   I have the 2.1.4 version 

@hscissors  you say that AppCompat is the way.   Is too bad my entire project is based on Holo theme . So Do you know if they will fix this issue for Holo theme ?

**Comment by daxeshzwt** [comment]
when i have used fullscreen theme , then n then this issues happening so can you please help me that which theme i will use for that.

recomnded one of themes

**Comment by daxeshzwt** [comment]
Add these style into your values -> style : 
 
<style name="Theme.AppCompat.Light.NoActionBar.FullScreen" parent="@style/Theme.AppCompat.Light">
        <item name="windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowContentOverlay">@null</item>
    </style>


Add these style into your Activity  tag or application tag:: 

android:theme="@style/Theme.AppCompat.Light.NoActionBar.FullScreen"

**Comment by lolobosse** [comment]
@daxeshzwt I confirm that your solution fixed the problem I got on a Samsung 4.4 👍 😄

**Comment by hsuanyu0304** [comment]
@daxeshzwt Thank you, I fixed the problem by your sloution too. 
But why? 
Why it works when I added [ true false true @null ] in my style?

**Comment by IDFDeveloper** [comment]
I am facing the same issue and after spending more than 4 hours and I solved the issue by adding this property in the `AndroidManifest.xml` file. I know it is different but it is working for me in the Samsung device.

> android:hardwareAccelerated="true"
